name: build hosts

# catch issues that flake check doesn't

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [mitsu8, minato, suzaku, inaho, minamo, dev-vm]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v15
        with:
          name: nyiyui-etc-nixos
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix-prefetch-url --name displaylink-620.zip https://www.synaptics.com/sites/default/files/exe_files/2025-09/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu6.2-EXE.zip
      - name: build ${{ matrix.host }}
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel
