name: nix flake update (daily)
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake lock --update-input jks
      - run: nix flake lock --update-input seekback-server
      - run: nix flake lock --update-input qrystal
      - run: nix flake lock --update-input jts
      - name: commit and push
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'etc-nixos+github-actions@nyiyui.ca'
          if test -n $(git diff-index @); then
            git add flake.lock
            git commit -am "nix flake update (jks, seekback-server, qrystal)"
            git push
          fi
