name: nix flake check
on:
  push:

jobs:
  update:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/flake-checker-action@v8
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: "nix flake check"
