name: nixfmt
on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: check formatting
        run: "nix develop --command nixfmt --check */*.nix"
