name: check formatting
on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3
      - name: check formatting
        run: "nix develop --command nixfmt --check */*.nix"
