name: nixfmt
on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          gitub_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: "nix-shell -p nixfmt --run 'nixfmt */*.nix'"
      - name: commit and push
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'etc-nixos+github-actions@nyiyui.ca'
          git add flake.lock
          git commit -am "nixfmt"
          git push
